apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: toe-system
data:
  # Go time format string for organizing profiles by date
  # Default creates separate folders: year/month/day
  # Format: 2006/01/02 creates structure like: 2025/10/30/
  dateFormat: "2006/01/02"
