resources:
- configmap.yaml
- pvc.yaml
- deployment.yaml

# Optional: Add debug pod for development
# - debug-pod.yaml

images:
- name: localhost:32000/codriverlabs/toe-collector
  newTag: v1.0.47
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
